### ISSUE TITLE
Breaking issue. Bypass Rules not working anymore after update 2.5.801

### ISSUE THREAD

**Issue by Inlustris** [BlueBasher/WorkItemUpdater#72] opened 2020-07-14 11:46 UTC
Hello after the update 2.5.801 originating from Azure DevOps the bypass rules does not work anymore. Now the WorkitemUpdater is not able to update tickets for me. Is it possible something in this update created a bug?

We use this in production and would like to fix it as soon as possible.

**Comment by Inlustris** [comment] 2020-07-17 13:39
@BlueBasher Is it possible to look at this ASAP? Would like to use it but now i have to bypass the step because it fails.

**Comment by rbrickey-rogue** [comment] 2021-11-08 17:45
We had a similar problem after updating Azure to use the "new URL" of dev.azure.com/organization instead of organization.visualstudio.com. The WorkItemUpdater would say it updated tickets but did not save any changes to the status. 

@Inlustris The updater will work as intended if you de-select the "bypass rules" checkbox. The "bypass rules" checkbox is no longer properly wired up to do what it is meant to do. I had to clone the WorkItemUpdater repo and compile it to find the problem (see below).

@BlueBasher  
On line 366 of _WorkItemUpdater.ts_, `settings.bypassRules` is passed into `workItemTrackingClient.updateWorkItem(...)` as the 5th parameter when it really should be the 6th. `validateOnly` is the 5th parameter, which tells the API not to save any changes from the request, so no updates are applied when the "bypass rules" checkbox is selected.

https://github.com/BlueBasher/WorkItemUpdater/blob/9275921d33422beb6e5702dccf84aa12eb609617/src/WorkItemUpdater/WorkItemUpdater.ts#L366

From _src\WorkItemUpdater\node_modules\azure-devops-node-api\WorkItemTrackingApi.d.ts_:
![image](https://user-images.githubusercontent.com/56696265/140791724-0850f01f-54c6-4e14-9696-8b35d06cd4eb.png)

**Comment by BlueBasher** [comment] 2021-11-26 18:59
A new version has now been released with this fix, had some issues with the release pipelines... Thanks for the help with this @rbrickey-rogue

**Closed by BlueBasher** 2021-11-26 18:59 UTC
