### ISSUE TITLE
Not updating status when having multiple build artifacts

### ISSUE THREAD

**Issue by JimWolff** [BlueBasher/WorkItemUpdater#51] opened 2019-06-11 10:02 UTC
When you have a release pipeline that uses several build artifacts, only items that are in **both** artifacts have their status updated. (using diff between deployment as source of workitems)

For me it seems like the default behavior should be that workitems in any of the build artifacts should be updated.

An option to toggle this behavior could also be provided, but just reversing the way it works today would fix any issue in my opinion (otherwise it's counter intuitive)

**Comment by mbulava** [comment] 2019-07-05 07:14
Agree with this. I continually get message "No workitems found to update." but I know there are workitems that are associated to the Builds/Release when I look at them..

**Comment by Jonlondon** [comment] 2019-07-18 12:16
I agree. Same issue.

**Comment by BlueBasher** [comment] 2020-07-09 05:49
Have you tried this when enabling the checkbox "Include workitems since previously completed deployment"?

**Comment by BlueBasher** [comment] 2020-07-09 05:53
Closing this as it's a duplicate of #62

**Closed by BlueBasher** 2020-07-09 05:53 UTC
